/**
 * Deterministic fix strategies. Each strategy is a mechanical, AST-shaped source
 * transform plus a vulnerability predicate and a proof-of-fix test generator.
 *
 * These are the AUTHORITATIVE, validated patch producers: the LLM may propose an
 * alternative (see generate.ts), but it is accepted only if it passes the same
 * predicate-flip + clean-apply validation these transforms guarantee. Detection
 * stays deterministic; the model only assists (golden rule #6).
 */
import type { Category, ConfirmedFinding } from "@montr/contracts";

export interface FixStrategy {
  readonly category: Category;
  /** true ⇒ the insecure pattern is present. Non-global regex (safe for .test). */
  vulnerable(source: string): boolean;
  /** Mechanical transform → fixed source, or `null` if it does not apply here. */
  apply(source: string): string | null;
  /** Default plain-English rationale for this class of fix. */
  readonly rationale: string;
  readonly testFramework: string;
  /** Synthesize the proof-of-fix test source for this file. */
  proofTestCode(filePath: string, finding: ConfirmedFinding): string;
}

/** Render a filesystem-reading vitest proof-of-fix test from vuln/safe signals. */
function renderProofTest(
  filePath: string,
  category: Category,
  vulnerable: RegExp,
  safe: RegExp | undefined,
): string {
  const lines = [
    `import { readFileSync } from "node:fs";`,
    `import { describe, it, expect } from "vitest";`,
    ``,
    `// Proof-of-fix test generated by @montr/fix (Layer 4) for ${category}.`,
    `// Run against the PATCHED working tree: FAILS before the patch, PASSES after.`,
    `const source = readFileSync(${JSON.stringify(filePath)}, "utf8");`,
    ``,
    `describe(${JSON.stringify(`proof-of-fix: ${category} @ ${filePath}`)}, () => {`,
    `  it("no longer contains the vulnerable pattern", () => {`,
    `    expect(source).not.toMatch(${vulnerable.toString()});`,
    `  });`,
  ];
  if (safe) {
    lines.push(
      `  it("uses the remediated pattern", () => {`,
      `    expect(source).toMatch(${safe.toString()});`,
      `  });`,
    );
  }
  lines.push(`});`, ``);
  return lines.join("\n");
}

interface RegexStrategyConfig {
  category: Category;
  vulnerable: RegExp;
  safe?: RegExp;
  transform(source: string): string;
  rationale: string;
  testFramework?: string;
}

function makeStrategy(config: RegexStrategyConfig): FixStrategy {
  const vulnerable = config.vulnerable;
  const safe = config.safe;
  return {
    category: config.category,
    vulnerable: (source: string): boolean => vulnerable.test(source),
    apply: (source: string): string | null => {
      const fixed = config.transform(source);
      return fixed === source ? null : fixed;
    },
    rationale: config.rationale,
    testFramework: config.testFramework ?? "vitest",
    proofTestCode: (filePath: string): string =>
      renderProofTest(filePath, config.category, vulnerable, safe),
  };
}

/** Strip the surrounding quotes from an interpolation, e.g. `'${q}'` → `${q}`. */
function stripQuotesAroundInterpolations(templateLiteral: string): string {
  return templateLiteral.replace(/'(\$\{[^}]*\})'/g, "$1").replace(/"(\$\{[^}]*\})"/g, "$1");
}

/** SQL injection — Prisma unsafe raw query → parameterized tagged template. */
const sqlInjectionStrategy = makeStrategy({
  category: "sql_injection",
  vulnerable: /\$(?:queryRawUnsafe|executeRawUnsafe)\b/,
  safe: /\$(?:queryRaw|executeRaw)`/,
  transform: (source) =>
    source
      .replace(
        /\$queryRawUnsafe\s*\(\s*(`[\s\S]*?`)\s*,?\s*\)/g,
        (_m, tmpl: string) => "$queryRaw" + stripQuotesAroundInterpolations(tmpl),
      )
      .replace(
        /\$executeRawUnsafe\s*\(\s*(`[\s\S]*?`)\s*,?\s*\)/g,
        (_m, tmpl: string) => "$executeRaw" + stripQuotesAroundInterpolations(tmpl),
      ),
  rationale:
    "Replaced the unsafe raw query (`$queryRawUnsafe`) with a parameterized `$queryRaw` tagged " +
    "template, so user input is bound as a query parameter and can never alter SQL structure.",
});

/** Reflected XSS — dangerouslySetInnerHTML → auto-escaped JSX text. */
const xssStrategy = makeStrategy({
  category: "xss",
  vulnerable: /dangerouslySetInnerHTML/,
  transform: (source) =>
    source.replace(
      /<(\w+)\s+dangerouslySetInnerHTML=\{\{\s*__html:\s*([\s\S]*?)\s*\}\}\s*\/>/g,
      (_m, tag: string, expr: string) => `<${tag}>{${expr.trim()}}</${tag}>`,
    ),
  rationale:
    "Rendered user input as auto-escaped JSX text instead of raw HTML (removed " +
    "`dangerouslySetInnerHTML`), so any injected markup is displayed inertly rather than executed.",
});

/** Permissive CORS — wildcard origin → explicit env-configured allowlist origin. */
const permissiveCorsStrategy = makeStrategy({
  category: "permissive_cors",
  vulnerable: /["']Access-Control-Allow-Origin["']\s*:\s*["']\*["']/,
  transform: (source) =>
    source.replace(
      /(["']Access-Control-Allow-Origin["']\s*:\s*)["']\*["']/g,
      '$1process.env.CORS_ALLOWED_ORIGIN ?? ""',
    ),
  rationale:
    "Replaced the wildcard CORS origin (`*`) with an explicit, env-configured allowlist origin so " +
    "the endpoint no longer opts every site into cross-origin reads.",
});

/**
 * Hard-coded secret — literal credential → `process.env` lookup. The PATCH is
 * mechanical, but merging is `human-required` (the leaked key must be rotated
 * and purged from history by a human — the risk classifier enforces this).
 */
const hardcodedSecretStrategy = makeStrategy({
  category: "hardcoded_secret",
  vulnerable: /["'](?:sk_live_|sk_test_)[A-Za-z0-9]+["']/,
  transform: (source) =>
    source.replace(
      /(\bconst\s+([A-Za-z0-9_]+)\s*=\s*)["'](?:sk_live_|sk_test_)[A-Za-z0-9]+["']/g,
      (_m, pre: string, name: string) => `${pre}process.env.${name} ?? ""`,
    ),
  rationale:
    "Replaced the hard-coded secret literal with a `process.env` lookup. NOTE: the exposed key must " +
    "still be ROTATED and purged from version-control history by a human — this fix prevents future " +
    "hard-coding but does not invalidate the already-leaked credential.",
});

/** All deterministic strategies, keyed by category via {@link pickStrategy}. */
export const FIX_STRATEGIES: readonly FixStrategy[] = [
  sqlInjectionStrategy,
  xssStrategy,
  permissiveCorsStrategy,
  hardcodedSecretStrategy,
];

/** The deterministic strategy for a category, if one exists. */
export function pickStrategy(category: Category): FixStrategy | undefined {
  return FIX_STRATEGIES.find((s) => s.category === category);
}

/** Placeholder proof-of-fix test for findings with no auto-validated fix. */
export function advisoryProofTestCode(filePath: string, finding: ConfirmedFinding): string {
  return [
    `import { describe } from "vitest";`,
    ``,
    `// ADVISORY: no auto-validated fix was produced. A human must implement the`,
    `// remediation for ${finding.category} at ${filePath} and replace this placeholder`,
    `// with a real proof-of-fix test (failing before the change, passing after).`,
    `describe.todo(${JSON.stringify(`proof-of-fix (manual): ${finding.category} @ ${filePath}`)});`,
    ``,
  ].join("\n");
}

/** Derive a sibling proof-of-fix test path for a source file. */
export function proofTestPath(filePath: string): string {
  return filePath.replace(/\.(tsx?|jsx?)$/i, "") + ".proof-of-fix.test.ts";
}
