import * as React from "react";
import type { GeneratedExecutiveSummary } from "@montr/contracts";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card.js";
import { Badge } from "./ui/badge.js";
import { toneClasses } from "../lib/format.js";

/**
 * A18 — the OPTIONAL, AI-generated narrative layered on top of the
 * deterministic report (`Report.generatedExecutiveSummary`). Rendered ONLY
 * when the field is present (reporting.executiveSummary.enabled was on for
 * this scan AND generation succeeded) — absent for every other scan, with no
 * placeholder shown.
 *
 * Deliberately visually distinct from `ExecSummary` (the audited,
 * template-assembled artifact of record just above it on the Report tab): a
 * dashed border, an "AI-GENERATED" badge, and the fixed disclaimer string
 * the schema itself carries, so this can never be mistaken for the
 * structured artifact.
 */
export function GeneratedExecutiveSummaryPanel({
  summary,
}: {
  summary: GeneratedExecutiveSummary;
}) {
  return (
    <Card className="border-dashed border-sky-500/40 bg-sky-500/5">
      <CardHeader>
        <div className="flex flex-wrap items-center gap-2">
          <CardTitle>AI-generated summary</CardTitle>
          <Badge className={toneClasses("info")}>AI-GENERATED</Badge>
        </div>
        <p className="text-sm text-muted-foreground">{summary.disclaimer}</p>
      </CardHeader>
      <CardContent className="space-y-4">
        <p className="text-sm leading-relaxed">{summary.narrative}</p>

        {summary.topPriorities.length > 0 ? (
          <div>
            <p className="mb-1.5 text-xs font-medium uppercase tracking-wide text-muted-foreground">
              Suggested focus areas
            </p>
            <ul className="list-disc space-y-1 pl-5 text-sm">
              {summary.topPriorities.map((item, i) => (
                <li key={i}>{item}</li>
              ))}
            </ul>
          </div>
        ) : null}

        <p className="text-xs text-muted-foreground">
          Generated by {summary.provider} · {summary.model} on{" "}
          {new Date(summary.generatedAt).toLocaleString()}. Not the audited artifact of record — see
          the confirmed findings below for that.
        </p>
      </CardContent>
    </Card>
  );
}
