/**
 * B3 — Sigma rule generation (github.com/SigmaHQ/sigma spec). One YAML rule
 * per confirmed finding, rendered from the shared `RuleContext` (context.ts)
 * so it always matches the SAME logic the OTel (otel.ts) and SIEM (siem.ts)
 * variants express.
 *
 * `logsource.category` follows two real, widely-used Sigma conventions:
 *  - "webserver" (route-shaped context: `live-request` / `static-request`) —
 *    the W3C-extended-log-format field names (`cs-method`, `cs-uri-stem`,
 *    `cs-uri-query`) that public Sigma web-attack rules key on.
 *  - "file_event" (the `file-fallback` context — a config/component-class
 *    finding with no resolved route) — `TargetFilename` is Sigma's standard
 *    field for this category (Sysmon EventID 11 and equivalents).
 *
 * Not hand-authored per finding — every field (`title`, `logsource`,
 * `detection`, `level`, `tags`) is derived mechanically from the
 * `ConfirmedFinding` + `RuleContext`, so two different findings always
 * produce two different rules, never a copy-pasted template.
 */
import type { ConfirmedFinding, Severity } from "@montr/contracts";
import type { RuleContext } from "./context.js";
import { deterministicUuid } from "./id.js";

const SIGMA_LEVEL: Record<Severity, string> = {
  info: "informational",
  low: "low",
  medium: "medium",
  high: "high",
  critical: "critical",
};

function yamlQuote(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function yamlList(items: string[], indent: string): string {
  return items.map((i) => `${indent}- ${yamlQuote(i)}`).join("\n");
}

function sigmaTags(finding: ConfirmedFinding, mitreTechniques: string[]): string[] {
  const tags = [`montr.category.${finding.category}`];
  if (finding.owasp) tags.push(`attack.${finding.owasp.toLowerCase().replace(/[:\s]/g, "-")}`);
  for (const cwe of finding.cwe) tags.push(`cwe.${cwe.toLowerCase().replace(/^cwe-/, "")}`);
  for (const t of mitreTechniques) tags.push(`attack.${t.toLowerCase()}`);
  return tags;
}

export function buildSigmaRule(
  finding: ConfirmedFinding,
  ctx: RuleContext,
  mitreTechniques: string[],
): string {
  const uuid = deterministicUuid(`sigma:${finding.id}`);
  const date = (finding.createdAt || new Date().toISOString()).slice(0, 10).replace(/-/g, "/");
  const level = SIGMA_LEVEL[finding.severity];
  const tags = sigmaTags(finding, mitreTechniques);

  const lines: string[] = [];
  lines.push(`title: ${yamlQuote(finding.title)}`);
  lines.push(`id: ${uuid}`);
  lines.push("status: experimental");
  lines.push(
    `description: ${yamlQuote(
      `Auto-generated by Montr Secure (B3) from ${ctx.provenanceNote}. ${finding.impact}`,
    )}`,
  );
  lines.push(`author: "Montr Secure"`);
  lines.push(`date: ${date}`);
  lines.push("references:");
  lines.push(`    - ${yamlQuote(`montr://finding/${finding.id}`)}`);

  if (ctx.kind === "file-fallback") {
    lines.push("logsource:");
    lines.push("    category: file_event");
    lines.push("detection:");
    lines.push("    selection:");
    lines.push(`        TargetFilename|contains: ${yamlQuote(ctx.fileTarget ?? "")}`);
    lines.push("    condition: selection");
  } else {
    lines.push("logsource:");
    lines.push("    category: webserver");
    lines.push("detection:");
    lines.push("    selection_route:");
    lines.push(`        cs-uri-stem|startswith: ${yamlQuote(ctx.path)}`);
    if (ctx.method !== "ANY") {
      lines.push(`        cs-method: ${yamlQuote(ctx.method)}`);
    }
    if (ctx.markers.length > 0) {
      lines.push("    selection_payload_query:");
      lines.push("        cs-uri-query|contains:");
      lines.push(yamlList(ctx.markers, "            "));
      lines.push("    selection_payload_body:");
      lines.push("        cs-body|contains:");
      lines.push(yamlList(ctx.markers, "            "));
      lines.push("    condition: selection_route and 1 of selection_payload_*");
    } else {
      lines.push("    condition: selection_route");
    }
  }

  lines.push(`falsepositives:`);
  lines.push(
    `    - ${yamlQuote("See this rule's DetectionRule.logSignature.falseAlarmSources (B4).")}`,
  );
  lines.push(`level: ${level}`);
  lines.push("tags:");
  lines.push(yamlList(tags, "    "));

  return `${lines.join("\n")}\n`;
}
