apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "montr.fullname" . }}-api
  labels:
    {{- include "montr.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "montr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "montr.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      serviceAccountName: {{ include "montr.serviceAccountName" . }}
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: {{ include "montr.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["dist/index.js"]
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
          envFrom:
            - configMapRef:
                name: {{ include "montr.fullname" . }}-config
            - secretRef:
                name: {{ include "montr.secretName" . }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.api.port }}
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: {{ .Values.api.port }}
            initialDelaySeconds: 20
            periodSeconds: 30
