apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "montr.fullname" . }}-worker
  labels:
    {{- include "montr.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "montr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "montr.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "montr.serviceAccountName" . }}
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: worker
          image: {{ include "montr.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["dist/index.js"]
          envFrom:
            - configMapRef:
                name: {{ include "montr.fullname" . }}-config
            - secretRef:
                name: {{ include "montr.secretName" . }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
