apiVersion: v1
kind: Service
metadata:
  name: {{ include "montr.fullname" . }}-web
  labels:
    {{- include "montr.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "montr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.port }}
      targetPort: http
